### ISSUE TITLE
Consider making some fields exported to allow mixing high and low level interactions

### ISSUE THREAD

**Issue by arodland** [jfreymuth/pulse#13]
There are some ops that are unimplemented on the high-level stream objects (for instance getting latency, or setting dynamic sample rate). They're usable through proto, but then *everything* has to be done through proto. If for instance the `index` field on streams was public, then I could use `RawRequest` to do not-yet-implemented operations on those streams.

**Comment by jfreymuth** [comment]
I added methods for the stream index of record and playback streams, are any other fields needed?

**Comment by arodland** [comment]
I guess you'd know better than me. Nothing I know of right now :)

**Comment by jfreymuth** [comment]
I'll just wait for people to open more issues if i missed anything :D
