### ISSUE TITLE
Short writes to a playback stream can cause high CPU consumption

### ISSUE THREAD

**Issue by arodland** [jfreymuth/pulse#15]
Thanks to the recent changes, I've got my app 99% working. However, the change to the playback interface doesn't *quite* work right.

Suppose my callback gets a request for 3000 samples, and it delivers 2048, because that's what it has available right now. `p.requested` will become 952, and `run` will immediately loop around and call my callback again with a request for 952 (or more). This will probably fail, and I will return 0, and the loop in `run` will spin at 100% CPU on calls to my callback and nonblocking channel reads, until my buffer fills again.

The only time it ever settles down is if the callback delivers exactly as many bytes as requested, and the nonblock read fails, in which case `run` will exit that loop and block on the channel read in the outer loop.

Locally modifying playback.go to add

```
if n == 0 {
    break
}
```

immediately before the select at line 103 doesn't cause any problems on my system, and brings CPU usage down to where it should be. Pulse always seems willing to deliver another request before it gets to an underrun.

**Comment by jfreymuth** [comment]
The documentation of io.Reader says:

> Implementations of Read are discouraged from returning a zero byte count with a nil error

meaning your callback should always block if there is no data available.

To see the problem with your suggested modification, try https://gist.github.com/jfreymuth/762dcec9afed10eeec34810a4a4118a4  
My guess is that the server keeps track of the number of bytes requested and will never send requests if that number is above a certain threshold (`BufferMaxLength - BufferMinimumRequest`?)

**Comment by arodland** [comment]
Granted, and I *can* block, but I *can't* always deliver the exact number of samples requested, and I can't deliver anything at all if the request is less than a certain size (without adding another ring-buffer in the client, which seems excessive). Maybe if the loop was `for requested >= BufferMinimumRequest` ?

**Comment by arodland** [comment]
Nevermind, I found a way around. I still think this is a potential pitfall, but I don't need a change here.
