### ISSUE TITLE
Closing connection during message read could lead to unbounded memory growth

### ISSUE THREAD

**Issue by leejuyuu** [jfreymuth/pulse#30]
I (mistakenly) called `pulse.Client.Close()` and `pulse.Client.ListSources()` concurrently in an app, and it led to unbounded memory growth followed by OOM kill. 

The following code can reproduce this problem. To make it easier to win the race, I created lots of null-sinks.

```go
package pulse_test

import (
	"testing"
	"time"

	"github.com/jfreymuth/pulse"
)

func TestReadLoopRace(t *testing.T) {
	for i := 0; i < 100; i++ {
		client, err := pulse.NewClient()
		if err != nil {
			t.Log(err)
			continue
		}

		go func() {
			time.Sleep(50 * time.Microsecond)
			client.Close()
		}()

		_, err = client.ListSources()
		if err != nil {
			t.Log(err)
			continue
		}
	}

	select {}
}
```

The problem originates from the `ProtocolReader` methods ignores errors, and returns zero values instead, without advancing the reader position. For example,

https://github.com/jfreymuth/pulse/blob/2ebf34ff11f265c8ba8f6b56e09e298968ab4170/proto/reader.go#L65-L73

When `Client.Close()` is called during the for loop inside `proto.Client.parseInfoList()`, the call to `ProtocolReader.value()` never increases `pos`, so the loop becomes an infinite loop. The creation of a struct on each iteration eats up the memory.

https://github.com/jfreymuth/pulse/blob/2ebf34ff11f265c8ba8f6b56e09e298968ab4170/proto/client.go#L233-L244

**Comment by leejuyuu** [comment]
I think the library would benefit from adding some safeguards. I would love to send patches. But I am unsure why the `ProtocolReader` was designed to store last error instead of make the methods return error.

**Comment by jfreymuth** [comment]
The Idea behind the design of the `ProtocolReader` is to make the protocol code more readable by avoiding constant `if err != nil {return...}` checks.  
By storing the error in the Reader and making sure zero values don't cause crashes, it is usually enough to check the error at the end of an operation and discard the result if there was an error. Obviously I failed at the second part here.

The safeguard that is missing is to check the error in every loop condition to avoid infinite loops.  
So for example pulse/proto/client.go line 235 should be:
```
 	for c.r.err == nil && c.r.pos-start < length { 
```

Patches would be very welcome
